version: '3.6'
services:
  aerospike:
    image: "aerospike/aerospike-server:4.9.0.5"
    environment:
      NAMESPACE: dev
    expose:
      - "3000"
  kafka:
    image: "spotify/kafka"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    expose:
      - "9092"
    ports:
      - "127.0.0.1:9092:9092"
  flink-jobmanager:
    image: "flink:1.10.0-scala_2.12"
    expose:
      - "6123"
    ports:
      - "127.0.0.1:8081:8081"
    command: jobmanager
    volumes:
      - "./deploy/flink-jobmanager-dev.yaml:/opt/flink/conf/flink-conf.yaml"

  flink-taskmanager:
    image: "flink:1.10.0-scala_2.12"
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink-jobmanager
      - kafka
      - aerospike
    command: taskmanager
    volumes:
      - "./deploy/flink-taskmanager-dev.yaml:/opt/flink/conf/flink-conf.yaml"
      - "./deploy/artifacts-fetcher-dev.conf:/opt/streams/artifacts-fetcher.conf"
      - "./deploy/crawler-dev.conf:/opt/streams/crawler.conf"



